<?php

// File generated from our OpenAPI spec

namespace StripePhp\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \StripePhp\Account::OBJECT_NAME => \StripePhp\Account::class,
        \StripePhp\AccountLink::OBJECT_NAME => \StripePhp\AccountLink::class,
        \StripePhp\AlipayAccount::OBJECT_NAME => \StripePhp\AlipayAccount::class,
        \StripePhp\ApplePayDomain::OBJECT_NAME => \StripePhp\ApplePayDomain::class,
        \StripePhp\ApplicationFee::OBJECT_NAME => \StripePhp\ApplicationFee::class,
        \StripePhp\ApplicationFeeRefund::OBJECT_NAME => \StripePhp\ApplicationFeeRefund::class,
        \StripePhp\Balance::OBJECT_NAME => \StripePhp\Balance::class,
        \StripePhp\BalanceTransaction::OBJECT_NAME => \StripePhp\BalanceTransaction::class,
        \StripePhp\BankAccount::OBJECT_NAME => \StripePhp\BankAccount::class,
        \StripePhp\BillingPortal\Configuration::OBJECT_NAME => \StripePhp\BillingPortal\Configuration::class,
        \StripePhp\BillingPortal\Session::OBJECT_NAME => \StripePhp\BillingPortal\Session::class,
        \StripePhp\BitcoinReceiver::OBJECT_NAME => \StripePhp\BitcoinReceiver::class,
        \StripePhp\BitcoinTransaction::OBJECT_NAME => \StripePhp\BitcoinTransaction::class,
        \StripePhp\Capability::OBJECT_NAME => \StripePhp\Capability::class,
        \StripePhp\Card::OBJECT_NAME => \StripePhp\Card::class,
        \StripePhp\Charge::OBJECT_NAME => \StripePhp\Charge::class,
        \StripePhp\Checkout\Session::OBJECT_NAME => \StripePhp\Checkout\Session::class,
        \StripePhp\Collection::OBJECT_NAME => \StripePhp\Collection::class,
        \StripePhp\CountrySpec::OBJECT_NAME => \StripePhp\CountrySpec::class,
        \StripePhp\Coupon::OBJECT_NAME => \StripePhp\Coupon::class,
        \StripePhp\CreditNote::OBJECT_NAME => \StripePhp\CreditNote::class,
        \StripePhp\CreditNoteLineItem::OBJECT_NAME => \StripePhp\CreditNoteLineItem::class,
        \StripePhp\Customer::OBJECT_NAME => \StripePhp\Customer::class,
        \StripePhp\CustomerBalanceTransaction::OBJECT_NAME => \StripePhp\CustomerBalanceTransaction::class,
        \StripePhp\Discount::OBJECT_NAME => \StripePhp\Discount::class,
        \StripePhp\Dispute::OBJECT_NAME => \StripePhp\Dispute::class,
        \StripePhp\EphemeralKey::OBJECT_NAME => \StripePhp\EphemeralKey::class,
        \StripePhp\Event::OBJECT_NAME => \StripePhp\Event::class,
        \StripePhp\ExchangeRate::OBJECT_NAME => \StripePhp\ExchangeRate::class,
        \StripePhp\File::OBJECT_NAME => \StripePhp\File::class,
        \StripePhp\File::OBJECT_NAME_ALT => \StripePhp\File::class,
        \StripePhp\FileLink::OBJECT_NAME => \StripePhp\FileLink::class,
        \StripePhp\Identity\VerificationReport::OBJECT_NAME => \StripePhp\Identity\VerificationReport::class,
        \StripePhp\Identity\VerificationSession::OBJECT_NAME => \StripePhp\Identity\VerificationSession::class,
        \StripePhp\Invoice::OBJECT_NAME => \StripePhp\Invoice::class,
        \StripePhp\InvoiceItem::OBJECT_NAME => \StripePhp\InvoiceItem::class,
        \StripePhp\InvoiceLineItem::OBJECT_NAME => \StripePhp\InvoiceLineItem::class,
        \StripePhp\Issuing\Authorization::OBJECT_NAME => \StripePhp\Issuing\Authorization::class,
        \StripePhp\Issuing\Card::OBJECT_NAME => \StripePhp\Issuing\Card::class,
        \StripePhp\Issuing\CardDetails::OBJECT_NAME => \StripePhp\Issuing\CardDetails::class,
        \StripePhp\Issuing\Cardholder::OBJECT_NAME => \StripePhp\Issuing\Cardholder::class,
        \StripePhp\Issuing\Dispute::OBJECT_NAME => \StripePhp\Issuing\Dispute::class,
        \StripePhp\Issuing\Transaction::OBJECT_NAME => \StripePhp\Issuing\Transaction::class,
        \StripePhp\LineItem::OBJECT_NAME => \StripePhp\LineItem::class,
        \StripePhp\LoginLink::OBJECT_NAME => \StripePhp\LoginLink::class,
        \StripePhp\Mandate::OBJECT_NAME => \StripePhp\Mandate::class,
        \StripePhp\Order::OBJECT_NAME => \StripePhp\Order::class,
        \StripePhp\OrderItem::OBJECT_NAME => \StripePhp\OrderItem::class,
        \StripePhp\OrderReturn::OBJECT_NAME => \StripePhp\OrderReturn::class,
        \StripePhp\PaymentIntent::OBJECT_NAME => \StripePhp\PaymentIntent::class,
        \StripePhp\PaymentLink::OBJECT_NAME => \StripePhp\PaymentLink::class,
        \StripePhp\PaymentMethod::OBJECT_NAME => \StripePhp\PaymentMethod::class,
        \StripePhp\Payout::OBJECT_NAME => \StripePhp\Payout::class,
        \StripePhp\Person::OBJECT_NAME => \StripePhp\Person::class,
        \StripePhp\Plan::OBJECT_NAME => \StripePhp\Plan::class,
        \StripePhp\Price::OBJECT_NAME => \StripePhp\Price::class,
        \StripePhp\Product::OBJECT_NAME => \StripePhp\Product::class,
        \StripePhp\PromotionCode::OBJECT_NAME => \StripePhp\PromotionCode::class,
        \StripePhp\Quote::OBJECT_NAME => \StripePhp\Quote::class,
        \StripePhp\Radar\EarlyFraudWarning::OBJECT_NAME => \StripePhp\Radar\EarlyFraudWarning::class,
        \StripePhp\Radar\ValueList::OBJECT_NAME => \StripePhp\Radar\ValueList::class,
        \StripePhp\Radar\ValueListItem::OBJECT_NAME => \StripePhp\Radar\ValueListItem::class,
        \StripePhp\Recipient::OBJECT_NAME => \StripePhp\Recipient::class,
        \StripePhp\RecipientTransfer::OBJECT_NAME => \StripePhp\RecipientTransfer::class,
        \StripePhp\Refund::OBJECT_NAME => \StripePhp\Refund::class,
        \StripePhp\Reporting\ReportRun::OBJECT_NAME => \StripePhp\Reporting\ReportRun::class,
        \StripePhp\Reporting\ReportType::OBJECT_NAME => \StripePhp\Reporting\ReportType::class,
        \StripePhp\Review::OBJECT_NAME => \StripePhp\Review::class,
        \StripePhp\SetupAttempt::OBJECT_NAME => \StripePhp\SetupAttempt::class,
        \StripePhp\SetupIntent::OBJECT_NAME => \StripePhp\SetupIntent::class,
        \StripePhp\ShippingRate::OBJECT_NAME => \StripePhp\ShippingRate::class,
        \StripePhp\Sigma\ScheduledQueryRun::OBJECT_NAME => \StripePhp\Sigma\ScheduledQueryRun::class,
        \StripePhp\SKU::OBJECT_NAME => \StripePhp\SKU::class,
        \StripePhp\Source::OBJECT_NAME => \StripePhp\Source::class,
        \StripePhp\SourceTransaction::OBJECT_NAME => \StripePhp\SourceTransaction::class,
        \StripePhp\Subscription::OBJECT_NAME => \StripePhp\Subscription::class,
        \StripePhp\SubscriptionItem::OBJECT_NAME => \StripePhp\SubscriptionItem::class,
        \StripePhp\SubscriptionSchedule::OBJECT_NAME => \StripePhp\SubscriptionSchedule::class,
        \StripePhp\TaxCode::OBJECT_NAME => \StripePhp\TaxCode::class,
        \StripePhp\TaxId::OBJECT_NAME => \StripePhp\TaxId::class,
        \StripePhp\TaxRate::OBJECT_NAME => \StripePhp\TaxRate::class,
        \StripePhp\Terminal\ConnectionToken::OBJECT_NAME => \StripePhp\Terminal\ConnectionToken::class,
        \StripePhp\Terminal\Location::OBJECT_NAME => \StripePhp\Terminal\Location::class,
        \StripePhp\Terminal\Reader::OBJECT_NAME => \StripePhp\Terminal\Reader::class,
        \StripePhp\ThreeDSecure::OBJECT_NAME => \StripePhp\ThreeDSecure::class,
        \StripePhp\Token::OBJECT_NAME => \StripePhp\Token::class,
        \StripePhp\Topup::OBJECT_NAME => \StripePhp\Topup::class,
        \StripePhp\Transfer::OBJECT_NAME => \StripePhp\Transfer::class,
        \StripePhp\TransferReversal::OBJECT_NAME => \StripePhp\TransferReversal::class,
        \StripePhp\UsageRecord::OBJECT_NAME => \StripePhp\UsageRecord::class,
        \StripePhp\UsageRecordSummary::OBJECT_NAME => \StripePhp\UsageRecordSummary::class,
        \StripePhp\WebhookEndpoint::OBJECT_NAME => \StripePhp\WebhookEndpoint::class,
    ];
}
